// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsbWCC-vx38uu8zBTI-_1DLMCqplUxbRM',
    appId: '1:160753750129:web:89dd2d54bab75229114bd0',
    messagingSenderId: '160753750129',
    projectId: 'evaluation-2e0ae',
    authDomain: 'evaluation-2e0ae.firebaseapp.com',
    storageBucket: 'evaluation-2e0ae.appspot.com',
    measurementId: 'G-FH74FYHEK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC29MBHvSRauHlC5T_2grffO724Vee-IBM',
    appId: '1:160753750129:android:38f40359ec1413e7114bd0',
    messagingSenderId: '160753750129',
    projectId: 'evaluation-2e0ae',
    storageBucket: 'evaluation-2e0ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVlntYFkvxmcFRuiZC7HH51q5_z1zRLFs',
    appId: '1:160753750129:ios:f1b2c584b96b63d0114bd0',
    messagingSenderId: '160753750129',
    projectId: 'evaluation-2e0ae',
    storageBucket: 'evaluation-2e0ae.appspot.com',
    iosBundleId: 'com.example.evaluationDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVlntYFkvxmcFRuiZC7HH51q5_z1zRLFs',
    appId: '1:160753750129:ios:41f57879ff56199a114bd0',
    messagingSenderId: '160753750129',
    projectId: 'evaluation-2e0ae',
    storageBucket: 'evaluation-2e0ae.appspot.com',
    iosBundleId: 'com.example.evaluationDashboard.RunnerTests',
  );
}
